### ISSUE TITLE
New release with clang fixes?

### ISSUE THREAD

**Issue by wezm** [majorkingleo/xstow#2]
Would be great to have a new versioned release published that includes commits since the last one. In particular it would be good to have bdcbdb6f6e0f35ed0a0df50f0a9d19441af9c866 and bb41a55e711925d0325577d5a9f84280ee9468e8 in a release for building with clang.

**Comment by majorkingleo** [comment]
Thanks for reminding me... done.

**Comment by wezm** [comment]
Thank you 👍
