### ISSUE TITLE
missing files in 1.1.1

### ISSUE THREAD

**Issue by RefurioAnachro** [majorkingleo/xstow#3]
version 1.1.1 seems to be missing some files, version 1.1.0 builds fine.
```
$ git clone https://github.com/majorkingleo/xstow.git
$ cd xstow
$ ./reconfigure.sh
$ make
[...]
main.cpp:6:10: fatal error: arg.h: No such file or directory
    6 | #include "arg.h"
```

**Comment by majorkingleo** [comment]
Hi, when you checking out from github you need to get all submodules by command:

 `cd xstow && git submodule update --init --recursive`

or cloning in one line

 `git clone --recurse-submodules --recurse-submodules git@github.com:majorkingleo/xstow.git`

**Comment by RefurioAnachro** [comment]
thank you for clarifying the documentation!
