### ISSUE TITLE
static build problems

### ISSUE THREAD

**Issue by RefurioAnachro** [majorkingleo/xstow#4]
The reconfigure.sh script doesn't pass on its arguments to configure, which makes it somewhat non-obvious how to set up a build with --without-curses or --enable-static. When I call ./configure with these flags, then build fails with a lengthy error message about undefined references. I'm on alpine with musl libc, maybe that makes a difference. Here's a Dockerfile to reproduce the problem:

```
FROM alpine

RUN apk update \
 && apk add automake autoconf bash g++ git libc-dev make \
 && rm -rf /var/cache/apk/*

# version 1.1.1 is missing files:
# main.cpp:6:10: fatal error: arg.h: No such file or directory
#     6 | #include "arg.h"
RUN git clone https://github.com/majorkingleo/xstow.git /src \
 && git -C /src checkout 1.1.0

RUN cd /src \
 && aclocal \
 && autoheader \
 && automake --add-missing \
 && autoconf \
 && ./configure --enable-static --without-curses \
 && make
```

Use like so:

`$ docker build --progress plain`

**Comment by majorkingleo** [comment]
Hi you should modify the line:
`RUN git clone https://github.com/majorkingleo/xstow.git /src 
 && git -C /src checkout 1.1.0`
to
`RUN git clone --recurse-submodules --recurse-submodules git@github.com:majorkingleo/xstow.git /src  && git -C /src checkout 1.1.0`

**Comment by RefurioAnachro** [comment]
Thanks again %-D
